### ISSUE TITLE
Rename cli commands format

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/digicert-cli#12]
@abunashir as discussed let's rename the cli commands by endpoint/object.

For example:

* `digicert find-order --order-id [id]` => `digicert order find --order-id [id]`
* `digicert reissue-order --order-id [id]` => `digicert order reissue --order-id [id]`
* `digicert list-duplicate-certificates --order-id [id]` => `digicert certificates list-duplicates --order-id [id]`

Let's also add a `help` command like this: `digicert [endpoint] help` and `digicert [endpoint] [action] help`.

Thanks!

**Comment by abunashir** [comment]
Thanks @ronaldtse, I will update the existing interfaces and will also add the `help` with details documentation.

**Comment by ronaldtse** [comment]
@abunashir is this ready to close now? Thanks!

**Comment by abunashir** [comment]
Yes, closing it now :)
