### ISSUE TITLE
Version bump for rubygems release

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/digicert-cli#34]
@abunashir let's bump the version and release this once #32 is complete!

**Comment by abunashir** [comment]
Sure, I guess we should also try to take a better approach to setup `Digicert API KEY` configuration, and once those are done then maybe do another release?

**Comment by ronaldtse** [comment]
Yup, sounds good. We can always have more releases :-)

**Comment by abunashir** [comment]
@ronaldtse : The gem is ready, and I already bumped the version to `0.2.0`, could you please do a `rake release` and push it to RubyGems?

**Comment by ronaldtse** [comment]
It's done. Thanks @abunashir !
