### ISSUE TITLE
Add command `certificate duplicate`

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/digicert-cli#49]
As from https://www.digicert.com/services/v2/documentation/order/duplicate,

> Use this endpoint to request a duplicate certificate for an order. A duplicate shares the expiration date as the existing certificate and is identical with the exception of the CSR and a possible change in the server platform and signature hash. The common name and sans need to be the same as the original order. Multi-Domain SSL Certs allow a san to be moved to the common name. Wildcard certs allow for additional sans (as long as they are subdomains of the wildcard).

This command should duplicate an order and allow a limited update to the CSR (server platform, signature hash, common name, sans).

**Comment by ronaldtse** [comment]
This endpoint takes identical parameters and provides identical response as `certificate reissue`.

**Comment by abunashir** [comment]
@ronaldtse: This is resolved in PR # 57, Please let me know if there is anything else on this one.
