### ISSUE TITLE
Feature request: Create a new order/Generate a new cert

### ISSUE THREAD

**Issue by theodotos** [riboseinc/digicert-cli#59]
I've been playing around with digicert cli and noticed that there are is no way to create a new order/generate a new certificate from a fresh CSR. Any plans for this?

**Comment by abunashir** [comment]
Hey @theodotos, thanks for opening this feature request. We do have a plan to add the `create` interface to the CLI, but there are couple of things we need to add on the `digicert` gem first and as soon as that's done then we can look into this feature, thanks!

**Comment by francescm** [comment]
A quick and dirty solution are some rakefile tasks on top of digicert gem (not digicert-cli): have a look at: [this fork](https://github.com/francescm/digicert/tree/rakefile)

**Comment by abunashir** [comment]
Hello @theodotos thanks again, just wanted to give you a quick update. We've added the order creation interface to the CLI now, next release will include this interface, please let us if there is anything else, Thanks!
