### ISSUE TITLE
"Generation of CSR" and "Fresh Cert Order" should not require --order-id

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/digicert-cli#63]
From an email from Alain sent to our email:

> I am working on a project and I'd like to utilize this repo https://github.com/riboseinc/digicert-cli

> After exploring it and testing it, couple of things I would like to clear up a bit:
> - Why is that the option `--order-id` is required before generating a *CSR*? As far as I have been using DigiCert, the order-id is used only for port-issuance tasks. So, in which case this repos is only useful for already existing orders within DigiCert?

> - For a fresh cert order, it appears that, again, `order-id` is required. Reading the DigiCert API documentation, this is not required or there is no way for the client to self assign an order-id for a new Order, unless if this digicert-cli was meant for DigiCert (employee - Admin. Referring to DigiCert employees), that makes all sense.

@abunashir could you help verify and perhaps loosen the restrictions? Thanks!

**Comment by abunashir** [comment]
@ronaldtse, I had a quick look at the cli gem and looks like for some reason we've made the order id required and we are dependent on it to fetch some missing details while generating a new CSR (eg: organization, common name).

But now that you point it out, it's actually should not be required, and we should simply pass those details as cli arguments, and if missing then use the order id to fetch the details.

I've added this one to my todo's, and I will try to add this one as soon as possible, and will keep you updated, thanks!

**Comment by ronaldtse** [comment]
Thanks @abunashir!

**Comment by abunashir** [comment]
@ronaldtse, the attached PR fixes these issues, once it's merged then a user can generate a CSR without needing to provide the `order_id`.

**Comment by abunashir** [comment]
I've also pushed this changes to ruby gems: https://rubygems.org/gems/digicert-cli/versions/0.5.0

**Comment by ronaldtse** [comment]
Thanks!

**Comment by ykcab** [comment]
Hi Everyone, thanks for working on this. I am the one who sent the initial email.

**Comment by ronaldtse** [comment]
Thanks for reporting the issue!
