### ISSUE TITLE
Replace `bin/digicert` with just `digicert` commands in README

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/digicert-cli#7]
As title, since the `digicert` executable will be installed in `$PATH` using bundler. Thanks @abunashir !

**Comment by ronaldtse** [comment]
@abunashir the gem is now distributed -- can we close this? Thanks!

**Comment by abunashir** [comment]
Sure, I have not tested the executable yet, but we should be good, and closing it now :)
